#!/bin/bash
# Copyright (c) 2000-2017 Synology Inc. All rights reserved.

. "/var/packages/MariaDB10/scripts/hooks/common"
CONFIG_FILE="/var/services/web/wordpress/wp-config.php"

if [ ! -e "$2" ]; then
	logger -p 0 "$0: $2 not exist!"
	exit 1
fi

[ ! -f "$CONFIG_FILE" ] && exit 0

user="$1"
dbuser="$(sed -n "s/define('DB_USER',\s*'\(.*\)');$/\1/p" < $CONFIG_FILE | UnquotePHP)"

[ "$user" != "$dbuser" ]  && exit 0

pw="$(cat "$2" | QuotePHP | QuoteSed)"
sed -i "s/^define('DB_PASSWORD'.*$/define('DB_PASSWORD',\'"$pw"\');/" $CONFIG_FILE
